---
- name: Add Node.js signing key
  apt_key:
    state: present
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add Node.js repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main
    - deb-src https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main

- name: Install Node.js
  apt:
    name:
      - nodejs
    state: present
    update_cache: true
