---
- name: Install Guest Additions dependencies
  apt:
    name:
      - build-essential
      - dkms
      - linux-headers-{{ ansible_kernel }}

- name: Download Guest Additions
  get_url:
    dest: /tmp
    url: http://download.virtualbox.org/virtualbox/5.2.16/VBoxGuestAdditions_5.2.16.iso
  register: response

- name: Create VBoxGuestAdditions directory
  file:
    path: /media/VBoxGuestAdditions
    state: directory

- name: Mount VBoxGuestAdditions
  mount:
    fstype: iso9660
    opts: loop,ro
    path: /media/VBoxGuestAdditions
    src: "{{ response.dest }}"
    state: mounted

- name: Install VBoxGuestAdditions
  command: VBoxGuestAdditions/VBoxLinuxAdditions.run
  args:
    chdir: /media
  ignore_errors: true

- name: Remove VBoxGuestAdditions ISO
  file:
    path: "{{ response.dest }}"
    state: absent

- name: Unmount VBoxGuestAdditions
  mount:
    path: /media/VBoxGuestAdditions
    state: unmounted

- name: Remove VBoxGuestAdditions directory
  file:
    path: /media/VBoxGuestAdditions
    state: absent
